"""ADD: group unique

Revision ID: 1530aca93b6c
Revises: d72b2aba4242
Create Date: 2020-06-23 12:55:53.577298+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1530aca93b6c'
down_revision = 'd72b2aba4242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_groups_group', table_name='groups')
    op.create_index(op.f('ix_groups_group'), 'groups', ['group'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_group'), table_name='groups')
    op.create_index('ix_groups_group', 'groups', ['group'], unique=False)
    # ### end Alembic commands ###
