"""create table

Revision ID: d72b2aba4242
Revises:
Create Date: 2020-06-22 18:30:09.418645+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72b2aba4242'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_group'), 'groups', ['group'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=50), nullable=True),
    sa.Column('groupId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupId'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'groupId')
    )
    op.create_index('word_and_groupId_idx', 'words', ['word', 'groupId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('word_and_groupId_idx', table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_groups_group'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
